task_tracker/task_tracker/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/',include('tasks.urls'))
]

task_tracker/tasks/urls.py
from django.urls import path
from . import views

app_name="tasks"
urlpatterns = [
    path('',views.index,name='index'),
    path('register',views.register, name='register'),
    path('login',views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('task_list',views.task_list,name="task_list"),
    path('tasks/<int:pk>',views.task_detail,name="task_detail"),
    path('task_create',views.task_create,name='task_create')

 ]
 

task_tracker/tasks/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    due_date = models.DateField()
    is_complete = models.BooleanField(default=False)

    def __str__(self):
        return self.title

task_tracker/tasks/views.py
from django.shortcuts import render,redirect
from .models import Task
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django import forms
# Create your views here.

class NewTaskForm(forms.Form):
    title=forms.CharField(label="New Task")
    description=forms.CharField(label="Description")
    due_date=forms.DateField()


def index(request):
    return render(request,'tasks/index.html')



def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('tasks:task_list')
    else:
        form = UserCreationForm()
    return render(request, 'tasks/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('tasks:task_list')
    else:
        form = AuthenticationForm()
    return render(request, 'tasks/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('tasks:login')

@login_required
def task_list(request):
    tasks = Task.objects.filter(user=request.user)
    return render(request, 'tasks/task_list.html', {'tasks': tasks})

@login_required
def task_create(request):
    if request.method == 'POST':
        form=NewTaskForm(request.POST)
        if form.is_valid():
            title=form.cleaned_data["title"]
            description = form.cleaned_data['description']
            due_date=form.cleaned_data['due_date']
            task = Task.objects.create(title=title, description=description, due_date=due_date, user=request.user)
            return redirect('tasks:task_list')
        else:
             return render(request,"tasks/task_create.html",{
               "form":form 
            }) 
    return render(request, 'tasks/task_create.html',{
        "form":NewTaskForm()
    })

@login_required
def task_detail(request, pk):
    task = Task.objects.get(pk=pk)
    if task.user != request.user:
        raise Http404("You don't have permission to view this task.")
    return render(request, 'tasks/task_detail.html', {'task': task})

@login_required
def task_complete(request, pk):
    task = Task.objects.get(pk=pk)
    if task.user != request.user:
        raise Http404("You don't have permission to complete this task.")
    task.is_complete = True
    task.save()
    return redirect('task_list')


def task_incomplete(request, pk):
    task = Task.objects.get(pk=pk)
    if task.user!= request.user:
        raise Http404("You don't have permission to complete this task.")
    task.is_complete = False
    task.save()
    return redirect('task_list')

task_tracker/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}
{% block body %}
<p>
    {% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}!</p>
    <a  type="button" class="btn btn-primary" href="{% url 'tasks:task_create' %}">Add Task</a>
    <a  type="button" class="btn btn-primary" href="{% url 'tasks:task_list' %}">Task List</a>
    <a  type="button" class="btn btn-danger" href="{% url 'tasks:logout' %}">Logout</a>
{% else %}
    <p>You are not logged in.</p>
    <a  type="button" class="btn btn-primary" href="{% url 'tasks:login' %}">Login</a>
{% endif %}
</p>
{% endblock  %}

task_tracker/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href={% static 'tasks/styles.css' %}>
    <link rel="stylesheet" href={% static 'tasks/bootstrap.min.css' %}>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo App</title>
</head>
<body>
    <div class="content-wrapper">
        <header>
            <div class="container">
                <h1>Todo App</h1>
            </div>
        </header>
        <nav>   
        <div class="container">
        <ul>
            <li><a href="{% url 'tasks:index' %}">Home</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'tasks:task_list' %}">Tasks</a></li>
            <li><a href="{% url 'tasks:logout' %}">logout</a></li>
            {% endif %}
            <!-- Add more navigation items as needed -->
        </ul>
    </div>
    </nav>
    <main>
        <div class="container">
            {% block body %}
            {% endblock %}
        </div>
    </main>
    <footer>
        <div class="container">
            <p>&copy; 2024 Todo App</p>
        </div>
    </footer>
</body>
</html>

task_tracker/tasks/templates/tasks/login.html
{% extends "tasks/layout.html" %}
{% block body %}

{%if message %}
    <div>{{message}}</div>
{%endif%}    
    <form action={% url 'tasks:login' %} method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="password">
        <input type="submit" value="login">

    </form>
    <a href={% url 'tasks:register' %}>register</a>
{% endblock  %}

task_tracker/tasks/templates/tasks/register.html
{% extends "tasks/layout.html" %}
{% block body  %}  
<div class = "login">  
  
    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}        
    <h1>Register Here </h1>  
         <form method="post" >  
             {% csrf_token %}  
             <table>  
                {{ form.as_table }}  
                 <tr>  
                    <td></td>  
                    <td><input type="submit" name="submit" value="Register" /></td>  
                </tr>  
             </table>  
         </form>  
     </div>  
{% endblock  %}

task_tracker/tasks/templates/tasks/task_create.html
{% extends "tasks/layout.html" %}
{%block body%}
    <h1>New Task</h1>
    <form action="{% url 'tasks:task_create' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:task_list'%}">Tasks</a>
{%endblock%}    

task_tracker/tasks/templates/tasks/task_detail.html
{% extends "tasks/layout.html" %}
{% block body %}
<h1>{{task.title}}</h1>
<h2>{{task.due_date}}</h2>
<p>{{task.description}}</p>
<a href="{% url 'tasks:task_list'%}">Tasks</a>
{% endblock  %}

task_tracker/tasks/templates/tasks/task_list.html
{% extends "tasks/layout.html" %}
{%block body%}
<ul>
        <h1>{{request.user}}</h1>
{% for task in tasks%}
    
        <li>
                <a href={% url 'tasks:task_detail' task.pk %}>
                        {{task.title}}
                </a>
        </li>
{%empty%}
        <li>No Tasks</li>
{% endfor %}
</ul>
<a href="{% url 'tasks:task_create' %}">Add Task</a>
<a href={% url 'tasks:logout' %}>logout</a>
{% endblock %}